### ISSUE TITLE
[PE-D][Tester D] Adding duplicate persons

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T13-3/tp#138]
Currently, you cannot add 2 people with the same name into the app but u can add people with the same phone numbers and emails, which seems a little weird since phone numbers and email are unique while names are not.
![Screenshot 2024-04-05 at 4.10.12 PM.png](https://raw.githubusercontent.com/zhikaiong2001/ped/main/files/34d6e74d-2664-41c4-b337-94d57bd96bdf.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: zhikaiong2001/ped#1

**Comment by ibnu2651** [comment]
Duplicate #150
