### ISSUE TITLE
[PE-D][Tester B] Glitchy "Progress" text

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T13-3/tp#146]
After adding a client contact, the Progress word becomes glitchy:

![Screenshot 2024-04-05 at 4.19.16 PM.png](https://raw.githubusercontent.com/sun-ruiheng/ped/main/files/c0e4365e-2265-4427-a2be-ddc9129e9a89.png)

Very minor cosmetic bug, but good to fix for user experience nonetheless!

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: sun-ruiheng/ped#2

**Comment by justincred** [comment]
Tried to recreate following the steps, found the bug is true, will attempt to figure out reason
