### ISSUE TITLE
[PE-D][Tester C] Help command redirects to original AB3 UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T13-3/tp#183]
![image.png](https://raw.githubusercontent.com/tzaph/ped/main/files/22f16ab2-0978-4bbf-9f10-8d31da59377d.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: tzaph/ped#10

**Comment by ibnu2651** [comment]
Duplicate #154
